package com.motuts.usersProfiles.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "user_profiles")
public class UserProfile {

    private String id;
    private String userId;
    private String nickname;
    private String tipoPerfilId;
    private String fotoPerfil;

    public UserProfile() {
    }

    public UserProfile(String id, String userId, String tipoPerfilId) {
        this.id = id;
        this.userId = userId;
        this.tipoPerfilId = tipoPerfilId;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getUserId() {
        return userId;
    }

    @DynamoDBAttribute
    public String getTipoPerfilId() {
        return tipoPerfilId;
    }

    @DynamoDBAttribute
    public String getFotoPerfil() {
        return fotoPerfil;
    }

    @DynamoDBAttribute
    public String getNickname() { return nickname; }
}
